<?php
/**
 * Created by PhpStorm.
 * User: Vea
 * Date: 2019/03/26 026
 * Time: 09:33
 */

use PHPUnit\Framework\TestCase;

class throwFromTest extends TestCase{
	use \nx\parts\validator\filterThrow;
	protected $in;
	protected $source=[
		'cid'=>11,
		'did'=>12,
	];
	protected function setUp(){
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->in=new \nx\input();
		$this->in['query']=[
			'cid'=>1,
			'did'=>2,
		];
		$this->in['body']=[
			'cid'=>3,
			'did'=>4,
		];
		$this->in['cookie']=[
			'cid'=>9,
			'did'=>10,
		];
	}
	/**
	 * 取值
	 */
	public function testFrom(){
		//from query, key cid
		$value =$this->_nx_filter_get_value('cxxid', ['from'=>'query', 'key'=>['value'=>'cid']]);
		$this->assertEquals($value,$this->in->query('cid'));
		//from body, key cid
		$value =$this->_nx_filter_get_value('cxxid', ['from'=>'body', 'key'=>['value'=>'cid']]);
		$this->assertEquals($value,$this->in->body('cid'));
		//from body, key cxxid, no-exist
		$value =$this->_nx_filter_get_value('cxxid', ['from'=>'body']);
		$this->assertEquals($value,null);
		//from cookie, key cxxid, no-exist
		$value =$this->_nx_filter_get_value('cxxid', ['from'=>'cookie']);
		$this->assertEquals($value,null);
		//from array, key cid, 2
		$value =$this->_nx_filter_get_value('cxxid', ['from'=>$this->source, 'key'=>['value'=>'cid']]);
		$this->assertEquals($value,11);
		//from array, key cxxid, 1
		$value =$this->_nx_filter_get_value('cxxid', ['from'=>['cxxid'=>1]]);
		$this->assertEquals($value,1);
		//from array, key cxxid, no-exist
		$value =$this->_nx_filter_get_value('cxxid', ['from'=>[]]);
		$this->assertEquals($value,null);
	}
}