<?php
/**
 * Created by PhpStorm.
 * User: Vea
 * Date: 2019/04/17 017
 * Time: 09:14
 */

class deprecated extends \PHPUnit\Framework\TestCase{
	var $cls=null;
	public function setUp(){
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->cls =new class() implements \ArrayAccess, \Countable, \IteratorAggregate{
			use nx\base\o2, \nx\log\dump;
		};
	}
	public function testAutoload(){
		$this->assertEquals(true, method_exists($this->cls, 'count'));
		$this->assertEquals(true, method_exists($this->cls, 'log'));

		$this->assertEquals(null, $this->cls['a']);
		$this->cls['a'] =1;
		$this->cls['b'] =2;
		$this->assertEquals(2, $this->cls->count());
		$this->assertEquals(1, $this->cls['a']);
		$this->assertEquals(2, $this->cls['b']);
	}
}