<?php
/**
 * Created by PhpStorm.
 * User: Vea
 * Date: 2019/04/12 012
 * Time: 10:37
 */
use PHPUnit\Framework\TestCase;

class throwCheckTest extends TestCase{
	public $uri ='http://127.0.0.1/server.php?a=1';
	/**
	 * @var \nx\helpers\network\context
	 */
	public $req =null;
	public function setUp(){
		parent::setUp(); // TODO: Change the autogenerated stub

		//$this->req =\nx\network\context::request($this->uri);
		$this->req =new nx\helpers\network\context\request($this->uri);
	}
	public function testWork(){
		//$r =file_get_contents($this->uri);
		//var_dump($r);
		$this->req->method('post');

		//$this->req->body(['a'=>2, 'b'=>3, 'c'=>4, 'f'=>'@./server.php'], \nx\network\type::FORM_DATA);
		//$this->req->header('content-type', 'application/json');
		//$this->req->headers(['content-type'=> 'application/json']);
		$this->req->headers([
			'token'=> 'xxx-xxx-xxx',
			'content-type'=> 'application/json'
		]);
		$this->req->headers([
			'content-type'=> null
		]);

		//$r =$this->req->send(['a'=>2, 'b'=>3, 'c'=>4, 'f'=>'@../server.php'], \nx\network\type::FORM_DATA);
		//$r =$this->req->send(['a'=>2, 'b'=>3, 'c'=>4, 'f'=>'@../1555059371.png'], \nx\network\type::FORM_DATA);
		$r =$this->req->send(['a'=>2, 'b'=>3, 'c'=>4, 'f'=>[
			'file'=>'1.txt',
			'type'=>'text/plant',
			'content'=>'1234567',
		]], 'form');
		//$r =$this->req->send(['a'=>2, 'b'=>3, 'c'=>4, 'f'=>['']], \nx\network\type::FORM_DATA);
		$json =$r->asJson();
		$this->assertEquals('POST', $json['method']);
		$this->assertEquals(['a'=>'1'], $json['query']);
		$this->assertEquals(['a'=>'2', 'b'=>'3', 'c'=>'4'], $json['post']);


		//var_dump($json);
	}
	public function testLog(){
		$saveData =[];
		$log =function($data) use(&$saveData){
			$saveData[] =$data;
		};
		$this->req->setLog($log);
		$r =$this->req->send();
		$this->assertEquals([
			'request:',
            '  url:http://127.0.0.1/server.php?a=1',
			'  header:',
            [],
            '  body:',
            '',
            '  working: yes',
            '  status: 200',
		], $saveData);
	}

}