<?php
use PHPUnit\Framework\TestCase;

class classTest extends TestCase{
	public $config;
	protected function setUp():void{
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->config=new \nx\helpers\config\setup([
			'a'=>[
				'b'=>[
					'c'=>2,
				]
			]
		]);
	}
	public function testWork0(){
		$this->assertEquals(2, $this->config->get('a.b.c'));
	}
	public function testWork1(){
		$ok=$this->config->set('a.b.c', 1);
		$this->assertEquals(true, $ok);
		$this->assertEquals(['b'=>['c'=>1]], $this->config->get('a'));
		$this->assertEquals(['c'=>1], $this->config->get('a.b'));
		$this->assertEquals(1, $this->config->get('a.b.c'));
		$this->assertEquals(2, $this->config->get('a.b.c.d', 2));
		$this->assertEquals(2, $this->config->get('b', 2));
	}
	public function testWork2(){
		$this->config['a.b.c']=1;
		$this->assertEquals(['b'=>['c'=>1]], $this->config['a']);
		$this->assertEquals(['c'=>1], $this->config['a.b']);
		$this->assertEquals(1, $this->config['a.b.c']);
		$this->assertEquals(null, $this->config['a.b.c.d']);
		$this->assertEquals(null, $this->config['b']);
	}
}
