<?php
/**
 * Created by PhpStorm.
 * User: Vea
 * Date: 2019/03/26 026
 * Time: 09:33
 */

use PHPUnit\Framework\TestCase;

class pdoTest extends TestCase{
	use \nx\parts\db\pdo;
	var $setup =[];
	protected function setUp(){
		parent::setUp(); // TODO: Change the autogenerated stub
		//$this->db =new \nx\helpers\db\pdo([
		//	'dsn'=>'mysql:dbname=mysql;host=192.168.1.76;charset=utf8mb4',
		//	'username'=>'root',
		//	'password'=>'',
		//	'timeout'=>3,
		//	'options'=>[],
		//]);
		$this->setup['db/pdo']=[
			'default'=>[
				'dsn'=>'mysql:dbname=mysql;host=192.168.1.76;charset=utf8mb4',
				'username'=>'root',
				'password'=>'',
				'timeout'=>3,
				'options'=>[],
			]
		];
		$this->db()->setLog(function($x){
			var_dump($x);
		});
	}
	public function testWork(){
		//$x =$this->db->select(
		//	"SHOW COLUMNS FROM user"
		//);
		$user =$this->db()->from('user')->limit(10)->select()->where(['User'=>'root']);
		$x =$this->db()->select((string)$user, $user->params);

		$user =$this->db()->from('user', 'User')->limit(10)->select()->where('root');
		$y =$user->execute();

		$user =$this->db()->from('user');
		$user->limit(10)->select()->where($user['User']->equal('root'));
		$z =$user->execute();

		$this->assertEquals($x, $y);
		$this->assertEquals($x, $z);

	}
}
