<?php
/**
 * Created by PhpStorm.
 * User: Vea
 * Date: 2019/03/26 026
 * Time: 09:33
 */

use PHPUnit\Framework\TestCase;

define('AGREE_LICENSE', true);
class app extends \nx\app{
	use \nx\parts\db\pdo, \nx\log\dump;
	var $path =__DIR__;
}

class pdoTest extends TestCase{
	/**
	 * @var \nx\app
	 */
	var $app =null;
	protected function setUp(){
		parent::setUp(); // TODO: Change the autogenerated stub
		//$this->db =new \nx\helpers\db\pdo([
		//	'dsn'=>'mysql:dbname=mysql;host=192.168.1.76;charset=utf8mb4',
		//	'username'=>'root',
		//	'password'=>'',
		//	'timeout'=>3,
		//	'options'=>[],
		//]);
		$this->app =new app([
			'db/pdo'=>[
				'default'=>[
					'dsn'=>'mysql:dbname=mysql;host=192.168.1.76;charset=utf8mb4',
					'username'=>'root',
					'password'=>'',
					'timeout'=>3,
					'options'=>[],
				]
			]
		]);
		$this->app->db()->setLog(function($x){
			var_dump($x);
		});
	}
	public function testWork(){
		//$x =$this->db->select(
		//	"SHOW COLUMNS FROM user"
		//);
		$user =$this->app->db()->from('user')->limit(10)->select()->where(['User'=>'root']);
		$x =$this->app->db()->select((string)$user, $user->params);

		$user =$this->app->db()->from('user', 'User')->limit(10)->select()->where('root');
		$y =$user->execute();

		$user =$this->app->db()->from('user');
		$user->limit(10)->select()->where($user['User']->equal('root'));
		$z =$user->execute();

		$this->assertEquals($x, $y);
		$this->assertEquals($x, $z);

	}
}
